
run:
	echo 'liveinwater.cxt\n2\n2\ny\n1\nn\n' | python3 -m pynclose
run_bin:
	echo 'liveinwater.cxt\n2\n2\ny\n1\nn\n' | ../inclose_sources/Inclose

clean:
	- rm concepts.json context.cxt noConsByAsize.txt noConsByBsize.txt sorted.cxt
